export const levels = [
  [
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "            P           A   ",
      "                            ",
      "############################",
      "############################",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "            P           A   ",
      "                            ",
      "############################",
      "############################",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "            P           E   ",
      "                            ",
      "############################",
      "############################",
    ],
  ],
];

export const levelOptions = [
  {
    tileWidth: 64,
    tileHeight: 64,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      E: () => [sprite("exit"), area(), scale(1), "exit"],
      "#": () => [
        sprite("stone"),
        area(),
        scale(0.5),
        body({ isStatic: true }),
      ],
    },
  },
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      "#": () => [sprite("snow"), area(), body({ isStatic: true })],
    },
  },
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      "#": () => [sprite("grass"), area(), body({ isStatic: true })],
    },
  },
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      "#": () => [sprite("sand"), area(), body({ isStatic: true })],
    },
  },
];
