export const levels = [
  [
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A ",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A ",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A ",
      "##############",
    ],
  ],
  [
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
  ],
  [
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
  ],
  [
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
    [
      "              ",
      "              ",
      "              ",
      "              ",
      "              ",
      "    P       A",
      "##############",
    ],
  ],
];

export const levelOptions = [
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      B: () => [sprite("exit"), area(), scale(1), "exit"],
      "#": () => [sprite("autumnGround"), area(), body({ isStatic: true })],
      "-": () => [
        sprite("autumnGroundCenter"),
        area(),
        body({ isStatic: true }),
      ],
    },
  },
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      "#": () => [sprite("autumnGround"), area(), body({ isStatic: true })],
      "-": () => [
        sprite("autumnGroundCenter"),
        area(),
        body({ isStatic: true }),
      ],
    },
  },
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      "#": () => [sprite("autumnGround"), area(), body({ isStatic: true })],
      "-": () => [
        sprite("autumnGroundCenter"),
        area(),
        body({ isStatic: true }),
      ],
    },
  },
  {
    tileWidth: 128,
    tileHeight: 128,
    tiles: {
      A: () => [sprite("arrow"), area(), scale(1), "arrow"],
      P: () => [sprite("puzzle"), area(), scale(1), "puzzle"],
      "#": () => [sprite("autumnGround"), area(), body({ isStatic: true })],
      "-": () => [
        sprite("autumnGroundCenter"),
        area(),
        body({ isStatic: true }),
      ],
    },
  },
];
