export const images = {
  charAssets: ["./assets/chars/byte.png", "./assets/chars/byte.png"],
  puzzleAssets: ["./assets/pirate.png", "./assets/gold-ingots.png"],
  puzzleBgAssets: ["./assets/backgrounds/puzzle/paper_bg.png"],
  uiAssets: [
    "./assets/ui/close.png",
    "./assets/ui/floppy-disk.png",
    "./assets/ui/gear.png",
    "./assets/ui/google-classroom.png",
    "./assets/ui/info.png",
    "./assets/ui/podium.png",
    "./assets/ui/process.png",
    "./assets/ui/binary-code.png",
    "./assets/ui/chat.png",
    "./assets/ui/gear.png",
    "./assets/ui/arrow-down.png",
    "./assets/ui/arrow-up.png",
    "./assets/ui/arrow-right.png",
    "./assets/ui/arrow-left.png",
    "./assets/ui/down-arrow.png",
  ],
  chapterBgAssets: ["./assets/backgrounds/pxfuel.jpg"],
  bgAssets: [
    "./assets/backgrounds/pxfuel.jpg",
    "./assets/backgrounds/autumn_1.png",
    "./assets/backgrounds/autumn_2.png",
    "./assets/backgrounds/autumn_3.jpg",
  ],
  progressAssets: [
    "./assets/backgrounds/progress/1.png",
    "./assets/backgrounds/progress/2.png",
    "./assets/backgrounds/progress/3.png",
    "./assets/backgrounds/progress/4.png",
  ],
};
