export const images = {
  puzzleAssets: ["./assets/pirate.png", "./assets/gold-ingots.png"],
  puzzleBgAssets: ["./assets/paper_bg.png"],
  uiAssets: [
    "./assets/close.png",
    "./assets/floppy-disk.png",
    "./assets/gear.png",
    "./assets/google-classroom.png",
    "./assets/info.png",
    "./assets/podium.png",
    "./assets/process.png",
    "./assets/binary-code.png",
    "./assets/chat.png",
    "./assets/gear.png",
    "./assets/arrow-down.png",
    "./assets/arrow-up.png",
    "./assets/arrow-right.png",
    "./assets/arrow-left.png",
  ],
  chapterBgAssets: ["./assets/pxfuel.jpg"],
};
