export const images = {
  puzzleAssets: {
    byte_right: "./assets/chars/byte_right.png",
    byte_left: "./assets/chars/byte_left.png",
    program: "./assets/puzzle-assets/program.png",
    guard: "./assets/puzzle-assets/guard.png",
    cave: "./assets/puzzle-assets/cave.png",
    building: "./assets/puzzle-assets/building.png",
    bug: "./assets/puzzle-assets/bug.png",
    city: "./assets/puzzle-assets/city.png",
    backgrounds: {
      a_1: "./assets/backgrounds/puzzle/a_1.png",
      a_2: "./assets/backgrounds/puzzle/a_2.png",
      a_3: "./assets/backgrounds/puzzle/a_3.png",
      w_1: "./assets/backgrounds/puzzle/w_1.png",
      w_2: "./assets/backgrounds/puzzle/w_2.png",
      w_3: "./assets/backgrounds/puzzle/w_3.png",
      sg_1: "./assets/backgrounds/puzzle/sg_1.png",
      sg_2: "./assets/backgrounds/puzzle/sg_2.png",
      sg_3: "./assets/backgrounds/puzzle/sg_3.png",
      sm_1: "./assets/backgrounds/puzzle/sm_1.png",
      sm_2: "./assets/backgrounds/puzzle/sm_2.png",
      sm_3: "./assets/backgrounds/puzzle/sm_3.png",
    },
    ui: {
      up: "./assets/ui/arrow-up.png",
      down: "./assets/ui/arrow-down.png",
      left: "./assets/ui/arrow-left.png",
      right: "./assets/ui/arrow-right.png",
      light_off: "./assets/ui/tile_grey.png",
      light_fail: "./assets/ui/tile_red.png",
      light_success: "./assets/ui/tile_green.png",
    },
  },
  uiAssets: {
    close: "./assets/ui/close.png",
    info: "./assets/ui/info.png",
  },
  progressAssets: {
    autumn: "./assets/backgrounds/progress/1.png",
    winter: "./assets/backgrounds/progress/2.png",
    spring: "./assets/backgrounds/progress/3.png",
    summer: "./assets/backgrounds/progress/4.png",
  },
  eggAssets: {
    beetle: "./assets/egg/beetle.png",
    byte: "./assets/egg/byte_right.png",
    background: "./assets/egg/game_background_1.png",
  },
  overworld: {
    tutorialAssets: {
      tut_1: "./assets/overworld/tutorial/1.png",
      tut_2: "./assets/overworld/tutorial/2.png",
      tut_3: "./assets/overworld/tutorial/3.png",
      tut_4: "./assets/overworld/tutorial/4.png",
    },
    bgAssets: {
      a_1: "./assets/backgrounds/autumn_1.png",
      a_2: "./assets/backgrounds/autumn_2.png",
      a_3: "./assets/backgrounds/autumn_3.png",
      w_1: "./assets/backgrounds/winter_1.png",
      w_2: "./assets/backgrounds/winter_2.png",
      w_3: "./assets/backgrounds/winter_3.png",
      sg_1: "./assets/backgrounds/spring_1.png",
      sg_2: "./assets/backgrounds/spring_2.png",
      sg_3: "./assets/backgrounds/spring_3.png",
      sm_1: "./assets/backgrounds/summer_1.png",
      sm_2: "./assets/backgrounds/summer_2.png",
      sm_3: "./assets/backgrounds/summer_3.png",
    },
    char_assets: {
      char_idle: "./assets/overworld/player/theboy_idle.png",
      char_jump: "./assets/overworld/player/theboy_jump.png",
      char_walk: "./assets/overworld/player/theboy_walk.png",
    },
    ground: {
      ground_ss: "./assets/overworld/ground/spritesheet_ground.png",
    },
    items: {
      items_ss: "./assets/overworld/spritesheet_items.png",
      decorations_ss: "./assets/overworld/spritesheet_tiles.png",
    },
    ui: {
      music_note: "./assets/overworld/ui/music.jpeg",
      help_button: "./assets/overworld/ui/question.jpeg",
      button: "./assets/overworld/ui/button.png",
      next: "./assets/overworld/ui/next.png",
      previous: "./assets/overworld/ui/previous.png",
      close: "./assets/overworld/ui/cross.png",
    },
  },
};
